Cves Pug
hmcts/ccpay-bubble pull request #890
Opened 2024-05-28 12:07 UTC by Thor-tech-of-metal

Cves Pug

2024-05-28 13:32 UTC, davejones74 requested changes

2024-05-28 13:32 UTC, davejones74 commented on yarn-audit-known-issues
> +{"actions":[],"advisories":{"1096727":{"findings":[{"version":"2.88.0","paths":["request","request-promise-native>request","request-promise-native>request-promise-core>request"]}],"metadata":null,"vu
Can you change pug to version 3..0.3 and include it in the resolutions as I believe pug is also used in request. Can you also remove xlsx, that shouldn't be used anymore in pay-bubble.

2024-05-28 13:47 UTC, Thor-tech-of-metal commented on yarn-audit-known-issues
> +{"actions":[],"advisories":{"1096727":{"findings":[{"version":"2.88.0","paths":["request","request-promise-native>request","request-promise-native>request-promise-core>request"]}],"metadata":null,"vu
FIxed

2024-05-29 10:27 UTC, Ollie-Smith approved these changes
reviewed

2024-05-29 13:05 UTC, davejones74 approved these changes

2024-05-29 13:05 UTC, merged